# -*- coding: utf-8 -*-
"""Curated interview question bank for the mock interviewer.

Each question: q, points (what a strong answer covers — used for grading & feedback),
followups (probes the interviewer asks), level (1 easy · 2 medium · 3 hard).
Your own mined questions (Question Miner agent) are merged in at runtime.
"""

TRACKS = {
    "behavioral": {"name": "Behavioral (STAR)", "icon": "🗣️", "minutes": 4},
    "system-design": {"name": "System Design (HLD)", "icon": "🏗️", "minutes": 15},
    "lld": {"name": "Low-Level Design & OOP", "icon": "🧩", "minutes": 10},
    "dsa": {"name": "DSA — explain your approach", "icon": "🧠", "minutes": 6},
    "cs": {"name": "CS Fundamentals (OS · Networks)", "icon": "💻", "minutes": 3},
    "databases": {"name": "Databases & SQL", "icon": "🗄️", "minutes": 3},
    "distributed": {"name": "Distributed Systems", "icon": "🌐", "minutes": 4},
    "data-eng": {"name": "Data Engineering (Kafka · Flink · Spark)", "icon": "🌊", "minutes": 4},
    "java": {"name": "Java & JVM", "icon": "☕", "minutes": 3},
    "python": {"name": "Python", "icon": "🐍", "minutes": 3},
    "cloud": {"name": "Cloud, DevOps & Kubernetes", "icon": "☁️", "minutes": 3},
    "frontend": {"name": "JavaScript & Web", "icon": "🌐", "minutes": 3},
    "ml": {"name": "ML & GenAI Systems", "icon": "🤖", "minutes": 4},
}

BEHAVIORAL_THEMES = {
    "conflict": "Conflict / disagreement", "failure": "Failure / mistake", "leadership": "Leadership / influence",
    "ownership": "Ownership / going beyond", "ambiguity": "Ambiguity", "deadline": "Tight deadline / pressure",
    "customer": "Customer focus", "impact": "Biggest impact / proud of", "learning": "Learning fast",
    "feedback": "Receiving/giving feedback", "tradeoff": "Hard trade-off / technical decision", "mentoring": "Mentoring / helping others",
    "innovation": "Innovation / simplification", "dive-deep": "Debugging / dive deep", "priority": "Prioritisation",
}

Q = {}

Q["behavioral"] = [
    {"q": "Tell me about yourself.", "theme": "intro", "level": 1,
     "points": ["present role and scope in one line", "two or three highlights with measurable impact", "core technical strengths relevant to this role", "why you are looking now and why this company", "keep it under two minutes"],
     "followups": ["What are you most proud of in your current role?", "Why are you leaving?"]},
    {"q": "Tell me about a time you disagreed with a teammate or your manager.", "theme": "conflict", "level": 2,
     "points": ["specific situation and what was at stake", "you sought to understand their view first", "used data or a prototype to argue", "disagreed respectfully then committed", "outcome and relationship afterwards", "what you learned"],
     "followups": ["What would you do if you had been overruled?", "How did the relationship look afterwards?"]},
    {"q": "Describe a project that failed or a mistake you made.", "theme": "failure", "level": 2,
     "points": ["own the mistake without blaming others", "concrete impact of the failure", "how you detected and mitigated it", "root cause analysis", "process change so it never repeats", "measurable result after the change"],
     "followups": ["What would you do differently today?", "How did you communicate it to stakeholders?"]},
    {"q": "Tell me about a time you led a project without formal authority.", "theme": "leadership", "level": 2,
     "points": ["goal and why it mattered", "aligned stakeholders with a clear plan", "delegated and unblocked others", "handled resistance with data", "delivered result with metrics", "recognition of the team"],
     "followups": ["How did you handle someone who was not pulling their weight?"]},
    {"q": "Give an example of when you took ownership of something outside your job description.", "theme": "ownership", "level": 2,
     "points": ["noticed a problem nobody owned", "took initiative without being asked", "long-term thinking not just a quick fix", "measurable impact", "made it sustainable (docs, runbooks, handover)"],
     "followups": ["How did you balance it with your regular work?"]},
    {"q": "Tell me about a time you had to make a decision with incomplete information.", "theme": "ambiguity", "level": 2,
     "points": ["what was unknown and the deadline", "gathered the most important data quickly", "identified reversible vs irreversible decision", "made a call with stated assumptions", "set checkpoints to revisit", "outcome"],
     "followups": ["What would have changed your decision?"]},
    {"q": "Describe a time you delivered under a very tight deadline.", "theme": "deadline", "level": 1,
     "points": ["the deadline and why it was fixed", "cut scope ruthlessly and prioritized must-haves", "communicated risk early", "parallelized work", "quality safeguards kept", "result and follow-up cleanup"],
     "followups": ["What did you cut, and how did you decide?"]},
    {"q": "Tell me about a time you went above and beyond for a customer or user.", "theme": "customer", "level": 1,
     "points": ["who the customer was and their pain", "worked backwards from their need", "went beyond the ask", "measured customer outcome", "feedback loop"],
     "followups": ["How did you know it mattered to them?"]},
    {"q": "What is the most impactful project you have worked on?", "theme": "impact", "level": 2,
     "points": ["business context and problem", "your specific role and decisions", "technical depth: architecture and trade-offs", "quantified results (latency, cost, revenue, users)", "what you would improve"],
     "followups": ["What was the hardest technical decision?", "How did you measure success?"]},
    {"q": "Tell me about a time you had to learn a new technology quickly.", "theme": "learning", "level": 1,
     "points": ["why it was needed and the time frame", "learning strategy: docs, prototypes, experts", "applied it to deliver something real", "shared knowledge with the team", "result"],
     "followups": ["How do you keep up with technology in general?"]},
    {"q": "Tell me about a time you received critical feedback.", "theme": "feedback", "level": 1,
     "points": ["the specific feedback", "listened without being defensive", "action plan you created", "evidence of improvement", "you now seek feedback proactively"],
     "followups": ["Tell me about feedback you gave someone else."]},
    {"q": "Describe a difficult technical trade-off you made.", "theme": "tradeoff", "level": 3,
     "points": ["options considered", "criteria: latency, cost, complexity, time to market", "data or benchmarks used", "decision and who you aligned with", "consequences and whether it proved right"],
     "followups": ["If you had twice the time, would you choose differently?"]},
    {"q": "Tell me about a time you mentored or helped a colleague grow.", "theme": "mentoring", "level": 1,
     "points": ["who and what gap", "tailored approach: pairing, reviews, stretch tasks", "gave them ownership", "measurable growth", "what you learned about mentoring"],
     "followups": ["How do you handle an underperforming teammate?"]},
    {"q": "Tell me about a time you simplified a complex process or system.", "theme": "innovation", "level": 2,
     "points": ["the complexity and its cost", "insight that enabled simplification", "how you validated the idea", "rollout with low risk", "quantified improvement"],
     "followups": ["Did anyone push back?"]},
    {"q": "Tell me about the hardest bug or production incident you debugged.", "theme": "dive-deep", "level": 3,
     "points": ["symptoms and customer impact", "systematic hypothesis-driven debugging", "tools: logs, metrics, traces, profilers", "root cause", "fix plus prevention (tests, alerts, postmortem)", "time to resolution"],
     "followups": ["How did you communicate during the incident?", "What alert would have caught it earlier?"]},
    {"q": "How do you prioritize when you have multiple competing deadlines?", "theme": "priority", "level": 1,
     "points": ["impact versus effort framework", "align with manager and stakeholders", "communicate trade-offs explicitly", "say no or renegotiate scope", "concrete example"],
     "followups": ["Tell me about a time you had to say no."]},
    {"q": "Why do you want to work here?", "theme": "intro", "level": 1,
     "points": ["specific product or engineering challenge at this company", "connect to your experience", "culture or values that resonate with an example", "growth you expect", "genuine not generic"],
     "followups": ["What do you know about our engineering culture?"]},
    {"q": "Where do you see yourself in 3 to 5 years?", "theme": "intro", "level": 1,
     "points": ["technical growth direction", "scope and leadership ambitions", "connect to this role", "realistic and honest"],
     "followups": []},
]

Q["system-design"] = [
    {"q": "Design a URL shortener like TinyURL or bit.ly.", "level": 1,
     "points": ["clarify requirements: create, redirect, custom alias, expiry, analytics", "estimate: write QPS, read QPS 100:1, storage for 5 years", "API: POST /urls, GET /{code} returns 301 or 302", "key generation: base62 of counter or pre-generated key service vs hashing with collision check", "data store: key-value NoSQL, code as partition key", "cache hot codes in Redis, CDN at edge", "analytics asynchronously through a queue", "rate limiting and abuse prevention"],
     "followups": ["How do you avoid two servers generating the same code?", "301 vs 302 — which and why?", "How do you handle a celebrity link getting 1M hits per second?"]},
    {"q": "Design a news feed like Twitter/X or Instagram.", "level": 3,
     "points": ["requirements: post, follow, home timeline, latency target", "fan-out on write (push) vs fan-out on read (pull)", "hybrid: pull for celebrities with huge follower counts", "timeline cache per user in Redis, list of post IDs", "post storage sharded by post ID, media in object storage plus CDN", "ranking service and pagination with cursors", "async fan-out workers through a queue", "consistency is eventual and acceptable"],
     "followups": ["How do you handle a user with 100M followers?", "How do you rank the feed?", "How would you add ads?"]},
    {"q": "Design a chat application like WhatsApp or Slack.", "level": 3,
     "points": ["1:1 and group messaging, online presence, delivery and read receipts", "persistent connections with WebSockets and a connection gateway", "session service mapping user to gateway server", "message store: wide-column like Cassandra keyed by conversation and time", "message ordering with per-conversation sequence numbers", "offline delivery via push notifications and sync on reconnect", "group fan-out", "end-to-end encryption considerations"],
     "followups": ["How do you guarantee ordering?", "How do you scale presence?", "What happens when a gateway server dies?"]},
    {"q": "Design a rate limiter.", "level": 2,
     "points": ["where: client, API gateway, or service middleware", "algorithms: token bucket, leaky bucket, fixed window, sliding window log, sliding window counter", "distributed counters in Redis with atomic Lua or INCR with expiry", "per user, per IP, per API key rules", "return 429 with Retry-After headers", "race conditions and clock skew", "fail open vs fail closed"],
     "followups": ["Token bucket vs sliding window — when do you prefer which?", "How do you rate limit across multiple data centers?"]},
    {"q": "Design a distributed cache like Memcached or Redis cluster.", "level": 2,
     "points": ["API get, set, delete with TTL", "partitioning with consistent hashing and virtual nodes", "replication for availability", "eviction policies LRU or LFU", "cache-aside, write-through, write-back patterns", "hot key mitigation", "cache stampede protection with locks or request coalescing"],
     "followups": ["How do you handle a node failure?", "How do you keep cache and database consistent?"]},
    {"q": "Design a video streaming platform like YouTube or Netflix.", "level": 3,
     "points": ["upload service with resumable chunked uploads to object storage", "transcoding pipeline into multiple resolutions and bitrates via a DAG of workers", "adaptive bitrate streaming HLS or DASH", "CDN for delivery and edge caching", "metadata database and search", "view counts and recommendations asynchronously", "cost of storage and bandwidth"],
     "followups": ["How do you handle a viral video?", "How would you implement resume playback across devices?"]},
    {"q": "Design a ride-sharing service like Uber.", "level": 3,
     "points": ["rider request, driver matching, live location, trip lifecycle, payments", "location updates every few seconds from drivers", "geospatial index: geohash, quadtree or H3 cells", "matching service finds nearby available drivers", "trip state machine and consistency", "WebSockets for live tracking", "surge pricing", "payment idempotency"],
     "followups": ["How do you store and query millions of moving drivers?", "How do you prevent double-assigning a driver?"]},
    {"q": "Design a web crawler.", "level": 2,
     "points": ["seed URLs and a URL frontier with priority and politeness per host", "DNS resolution cache", "fetchers and parsers as distributed workers", "deduplicate URLs with a Bloom filter and content with fingerprints", "respect robots.txt and rate limits", "store content in object storage", "handle traps and infinite spaces", "recrawl scheduling by freshness"],
     "followups": ["How do you detect near-duplicate pages?", "How do you scale to a billion pages?"]},
    {"q": "Design a notification system (push, SMS, email).", "level": 2,
     "points": ["multiple channels and third-party providers", "notification service API with templates and user preferences", "queue per channel and workers", "retries with exponential backoff and dead-letter queue", "idempotency to avoid duplicates", "rate limiting and quiet hours", "tracking delivery and open events"],
     "followups": ["How do you guarantee at-least-once without spamming users?"]},
    {"q": "Design a key-value store like DynamoDB.", "level": 3,
     "points": ["partitioning with consistent hashing", "replication factor N with quorum reads and writes R + W > N", "sloppy quorum and hinted handoff", "conflict resolution with vector clocks or last-write-wins", "anti-entropy with Merkle trees", "gossip protocol for membership and failure detection", "storage engine LSM tree with memtable, SSTables and compaction"],
     "followups": ["Explain tunable consistency.", "What happens during a network partition?"]},
    {"q": "Design a search autocomplete / typeahead system.", "level": 2,
     "points": ["top-k suggestions per prefix with low latency", "trie with cached top-k at each node", "precompute offline from query logs with batch jobs", "serve from memory, shard by prefix", "update frequency and trending queries", "client-side debouncing and caching", "filtering offensive content"],
     "followups": ["How do you personalize suggestions?"]},
    {"q": "Design a payment system.", "level": 3,
     "points": ["payment flow with a PSP like Stripe", "idempotency keys for every request", "double-entry ledger as source of truth", "state machine for payment status", "reconciliation with PSP settlement files", "exactly-once effects via outbox pattern and dedupe", "strong consistency, ACID database", "security PCI and tokenization"],
     "followups": ["What happens if the PSP call times out?", "How do you handle refunds?"]},
    {"q": "Design a distributed job scheduler (like cron at scale).", "level": 2,
     "points": ["job definitions with schedules stored in database", "scheduler partitions jobs and enqueues due jobs", "leader election or partitioned ownership to avoid double scheduling", "workers pull from queue with visibility timeout", "retries, backoff and dead-letter", "at-least-once plus idempotent jobs", "monitoring of missed and late jobs"],
     "followups": ["How do you guarantee a job runs exactly once?"]},
    {"q": "Design a real-time analytics / metrics pipeline (like a clickstream dashboard).", "level": 3,
     "points": ["ingest events via Kafka partitioned by key", "stream processing with Flink using event time and watermarks", "windowed aggregations and late data handling", "exactly-once with checkpoints and transactional sinks", "serving store: OLAP like Druid, Pinot or ClickHouse", "cold path to data lake for batch reprocessing", "backpressure and scaling consumers"],
     "followups": ["How do you handle late arriving events?", "Lambda vs Kappa architecture?"]},
    {"q": "Design Google Drive / Dropbox.", "level": 3,
     "points": ["upload, download, sync across devices, sharing", "chunk files and deduplicate by chunk hash", "metadata database separate from blob storage", "sync service with change notifications via long polling or WebSockets", "conflict resolution creating conflicted copies", "versioning", "delta sync to save bandwidth"],
     "followups": ["How do you sync a 10GB file efficiently?"]},
    {"q": "Design a ticket booking system like BookMyShow or Ticketmaster.", "level": 3,
     "points": ["search events, view seat map, hold seats, pay, confirm", "seat hold with TTL to prevent double booking", "strong consistency using row locks or conditional writes", "virtual waiting room queue for flash sales", "payment integration and idempotency", "release seats on timeout", "caching read-heavy event data"],
     "followups": ["How do you handle 1M users trying to book a Taylor Swift concert at once?"]},
]

Q["lld"] = [
    {"q": "Design a parking lot system (classes and interactions).", "level": 2,
     "points": ["entities: ParkingLot, Level, Spot types, Vehicle types, Ticket, Payment", "strategy pattern for spot allocation", "enums for vehicle and spot sizes", "entry and exit gates with ticket issuing", "fee calculation strategy", "thread safety when assigning spots", "extensibility for new vehicle types"],
     "followups": ["How would you make spot assignment thread-safe?"]},
    {"q": "Design an LRU cache with O(1) get and put.", "level": 2,
     "points": ["hash map from key to node", "doubly linked list for recency order", "move to head on access", "evict tail when capacity exceeded", "sentinel head and tail nodes", "thread-safety options"],
     "followups": ["How would you design LFU?", "How to make it concurrent?"]},
    {"q": "Design an elevator system.", "level": 3,
     "points": ["Elevator, ElevatorController, Request, Direction, State", "scheduling algorithm: SCAN or LOOK", "internal vs external requests", "state pattern for moving, idle, maintenance", "multiple elevator dispatch strategy", "concurrency of requests"],
     "followups": ["How do you minimize average wait time?"]},
    {"q": "Explain the SOLID principles with examples.", "level": 1,
     "points": ["single responsibility: one reason to change", "open closed: extend without modifying", "Liskov substitution: subtypes honor contracts", "interface segregation: small focused interfaces", "dependency inversion: depend on abstractions", "concrete code example for each"],
     "followups": ["Give an example of a Liskov violation."]},
    {"q": "Design a vending machine.", "level": 2,
     "points": ["state pattern: Idle, HasMoney, Dispensing, OutOfStock", "inventory and product classes", "coin and note handling with change calculation", "cancel and refund", "thread safety"],
     "followups": ["How do you add card payment?"]},
    {"q": "Design Splitwise (expense sharing).", "level": 2,
     "points": ["User, Group, Expense, Split types: equal, exact, percent", "balance sheet map of who owes whom", "strategy for split types", "simplify debts with a greedy min-cash-flow algorithm", "validation of splits"],
     "followups": ["How do you minimize number of transactions?"]},
    {"q": "Which design patterns have you used in production and why?", "level": 1,
     "points": ["name specific patterns: strategy, factory, builder, observer, decorator, singleton, adapter", "concrete problem each solved", "trade-offs and when not to use", "code-level example"],
     "followups": ["Why is singleton often considered an anti-pattern?"]},
    {"q": "Design a logging framework like Log4j.", "level": 2,
     "points": ["Logger, Level, Appender, Formatter, LogManager", "chain of responsibility for levels", "observer or multiple appenders", "async logging with a buffer queue", "configuration", "thread safety"],
     "followups": ["How do you avoid blocking application threads?"]},
    {"q": "Design a thread-safe bounded blocking queue.", "level": 3,
     "points": ["array or linked buffer with capacity", "lock with two conditions notFull and notEmpty", "await in a while loop for spurious wakeups", "signal appropriately", "alternatives: semaphores", "compare with java.util.concurrent ArrayBlockingQueue"],
     "followups": ["Why a while loop instead of if around await?"]},
    {"q": "Composition vs inheritance — when do you use which?", "level": 1,
     "points": ["inheritance models is-a and couples tightly", "composition models has-a and is flexible", "favor composition over inheritance", "fragile base class problem", "example with strategy or decorator"],
     "followups": []},
]

Q["dsa"] = [
    {"q": "Given an array and a target, find two numbers that sum to the target. Walk me through your approach.", "level": 1,
     "points": ["brute force O(n^2) first", "hash map of value to index", "single pass checking complement", "O(n) time O(n) space", "two-pointer alternative if sorted", "edge cases: duplicates, no answer"], "followups": ["What if the array is sorted?", "What if we need all pairs?"]},
    {"q": "How would you find the longest substring without repeating characters?", "level": 2,
     "points": ["sliding window with two pointers", "hash map or set of last seen index", "shrink left when duplicate found", "O(n) time", "O(k) space for alphabet"], "followups": ["What if at most k distinct characters are allowed?"]},
    {"q": "How do you detect a cycle in a linked list, and find where it starts?", "level": 2,
     "points": ["Floyd's tortoise and hare", "fast moves 2 steps slow moves 1", "if they meet there is a cycle", "reset one pointer to head and move both one step to find start", "O(n) time O(1) space"], "followups": ["Why does the reset trick work?"]},
    {"q": "Explain how you would find the kth largest element in an array.", "level": 2,
     "points": ["sort O(n log n)", "min-heap of size k O(n log k)", "quickselect average O(n) worst O(n^2)", "randomized pivot", "trade-offs for streaming data"], "followups": ["What if the data is a stream?"]},
    {"q": "Number of islands in a grid — describe your solution.", "level": 2,
     "points": ["iterate cells, start DFS or BFS on unvisited land", "mark visited in place or with a set", "count components", "O(rows * cols) time", "union-find alternative", "recursion depth concern"], "followups": ["How would you handle a grid too large to fit in memory?"]},
    {"q": "How would you detect a cycle in a directed graph / course schedule?", "level": 2,
     "points": ["topological sort using Kahn's algorithm with in-degrees", "or DFS with three colors", "cycle exists if not all nodes are processed", "O(V + E)"], "followups": ["Return a valid order of courses."]},
    {"q": "Explain the coin change problem and how you'd solve it.", "level": 2,
     "points": ["greedy fails for arbitrary coin systems", "dynamic programming dp[amount] = min coins", "bottom-up iteration over amounts and coins", "O(amount * coins) time", "base case dp[0] = 0, unreachable as infinity"], "followups": ["Count the number of ways instead."]},
    {"q": "How would you merge k sorted lists?", "level": 3,
     "points": ["min-heap of current heads", "pop smallest and push its next", "O(N log k)", "divide and conquer pairwise merging alternative"], "followups": ["What if lists are on different machines?"]},
    {"q": "When do you use binary search beyond sorted arrays?", "level": 2,
     "points": ["binary search on the answer space", "monotonic predicate", "examples: Koko eating bananas, capacity to ship packages", "rotated sorted array", "careful with boundaries and overflow"], "followups": []},
    {"q": "Explain how you'd implement a trie and where it's useful.", "level": 2,
     "points": ["node with children map and end flag", "insert and search O(length)", "prefix queries", "autocomplete and word search", "memory trade-off"], "followups": []},
    {"q": "What's the difference between BFS and DFS and when do you use each?", "level": 1,
     "points": ["BFS uses a queue, explores level by level", "BFS gives shortest path in unweighted graphs", "DFS uses stack or recursion, explores deep", "DFS for topological sort, cycle detection, backtracking", "space characteristics differ"], "followups": []},
    {"q": "How do you approach a problem you've never seen before in an interview?", "level": 1,
     "points": ["clarify inputs, outputs, constraints", "work examples and edge cases", "state brute force", "identify pattern to optimize", "communicate complexity", "code cleanly then test with examples"], "followups": []},
]

Q["cs"] = [
    {"q": "What is the difference between a process and a thread?", "level": 1,
     "points": ["process has its own address space", "threads share memory within a process", "context switch cost higher for processes", "isolation and fault tolerance", "communication: IPC vs shared memory"], "followups": ["What do threads not share?"]},
    {"q": "What is a deadlock and how do you prevent it?", "level": 2,
     "points": ["four conditions: mutual exclusion, hold and wait, no preemption, circular wait", "prevent by global lock ordering", "timeouts and tryLock", "detection and recovery", "avoidance with banker's algorithm"], "followups": ["How would you debug a deadlock in production?"]},
    {"q": "Explain virtual memory and paging.", "level": 2,
     "points": ["each process sees its own virtual address space", "page table maps virtual pages to physical frames", "TLB caches translations", "page faults load from disk", "enables isolation and overcommit", "thrashing"], "followups": ["What is a TLB miss?"]},
    {"q": "What happens when you type a URL into the browser and press enter?", "level": 1,
     "points": ["DNS resolution with caches", "TCP handshake", "TLS handshake", "HTTP request", "load balancer and server processing", "response, rendering: HTML parse, CSS, JS, paint", "caching and CDN"], "followups": ["How does TLS establish a shared key?"]},
    {"q": "TCP vs UDP — differences and use cases.", "level": 1,
     "points": ["TCP connection-oriented, reliable, ordered", "flow and congestion control", "UDP connectionless, no guarantees, low overhead", "UDP for video, gaming, DNS", "QUIC builds reliability on UDP"], "followups": ["Why does HTTP/3 use UDP?"]},
    {"q": "Explain HTTP/1.1 vs HTTP/2 vs HTTP/3.", "level": 2,
     "points": ["HTTP/1.1 one request per connection at a time, keep-alive", "HTTP/2 multiplexing over one TCP connection, binary framing, header compression", "HTTP/2 still has TCP head-of-line blocking", "HTTP/3 over QUIC and UDP removes it", "faster handshakes"], "followups": []},
    {"q": "What is a mutex vs a semaphore?", "level": 1,
     "points": ["mutex provides mutual exclusion with ownership", "semaphore is a counter allowing N concurrent accesses", "binary semaphore vs mutex ownership difference", "use cases like connection pools"], "followups": []},
    {"q": "Explain CPU scheduling algorithms.", "level": 2,
     "points": ["FCFS, SJF, round robin, priority", "preemptive vs non-preemptive", "starvation and aging", "multilevel feedback queues", "Linux CFS"], "followups": []},
    {"q": "How does DNS work?", "level": 1,
     "points": ["hierarchy: root, TLD, authoritative", "recursive resolver", "caching and TTL", "record types A, AAAA, CNAME, MX", "DNS-based load balancing"], "followups": []},
    {"q": "Explain how HTTPS/TLS works.", "level": 2,
     "points": ["certificates and certificate authorities", "handshake negotiates cipher suite", "key exchange with Diffie-Hellman for forward secrecy", "symmetric encryption for bulk data", "integrity with MACs", "TLS 1.3 one round trip"], "followups": []},
]

Q["databases"] = [
    {"q": "Explain ACID properties.", "level": 1,
     "points": ["atomicity: all or nothing", "consistency: invariants preserved", "isolation: concurrent transactions don't interfere", "durability: committed data survives crashes via WAL", "examples"], "followups": ["How is durability implemented?"]},
    {"q": "What are transaction isolation levels and the anomalies they prevent?", "level": 2,
     "points": ["read uncommitted, read committed, repeatable read, serializable", "dirty reads, non-repeatable reads, phantom reads", "write skew under snapshot isolation", "MVCC implementation", "trade-off with performance"], "followups": ["What isolation level does Postgres use by default?"]},
    {"q": "How do database indexes work? When would an index not help?", "level": 2,
     "points": ["B+ tree index, sorted, logarithmic lookups", "hash indexes for equality", "composite index leftmost prefix rule", "covering indexes", "low selectivity columns don't benefit", "write overhead", "functions on columns prevent index use"], "followups": ["Clustered vs non-clustered index?"]},
    {"q": "SQL vs NoSQL — how do you choose?", "level": 1,
     "points": ["relational: schema, joins, ACID transactions", "NoSQL types: key-value, document, wide-column, graph", "horizontal scaling and flexible schema", "access pattern driven modeling", "consistency requirements"], "followups": []},
    {"q": "Explain database sharding and its challenges.", "level": 2,
     "points": ["split data horizontally across nodes", "shard key choice: range vs hash", "hot spots", "cross-shard joins and transactions are hard", "resharding with consistent hashing", "directory based sharding"], "followups": ["How do you reshard without downtime?"]},
    {"q": "Explain normalization and when you'd denormalize.", "level": 1,
     "points": ["1NF, 2NF, 3NF, BCNF remove redundancy", "avoid update anomalies", "denormalize for read performance", "data warehouses use star schemas"], "followups": []},
    {"q": "Write a SQL query to find the second highest salary / top N per group. Explain.", "level": 2,
     "points": ["window function DENSE_RANK or ROW_NUMBER partitioned by group", "subquery with MAX less than MAX alternative", "handle ties", "LIMIT OFFSET approach"], "followups": ["Difference between RANK, DENSE_RANK and ROW_NUMBER?"]},
    {"q": "How does replication work and what is replication lag?", "level": 2,
     "points": ["leader follower replication", "synchronous vs asynchronous", "read-your-writes problems due to lag", "multi-leader and leaderless replication", "failover and split brain"], "followups": []},
    {"q": "What is an LSM tree vs a B-tree?", "level": 3,
     "points": ["B-tree updates in place, good reads", "LSM writes to memtable and flushes sorted SSTables", "compaction", "write amplification vs read amplification", "Bloom filters for reads", "used by Cassandra, RocksDB"], "followups": []},
]

Q["distributed"] = [
    {"q": "Explain the CAP theorem and PACELC.", "level": 2,
     "points": ["consistency, availability, partition tolerance", "during a partition choose C or A", "PACELC: else latency vs consistency", "examples: CP like ZooKeeper, AP like Cassandra", "it's a spectrum and tunable"], "followups": []},
    {"q": "How does consistent hashing work and why is it useful?", "level": 2,
     "points": ["hash ring for nodes and keys", "key goes to next node clockwise", "adding or removing a node moves only K/N keys", "virtual nodes for balance", "used in Dynamo, Cassandra, caches"], "followups": []},
    {"q": "Explain the Raft consensus algorithm.", "level": 3,
     "points": ["leader election with terms and randomized timeouts", "log replication from leader", "commit when majority acknowledges", "safety: election restriction up-to-date logs", "used in etcd, Consul, KRaft"], "followups": ["What happens during a network partition?"]},
    {"q": "What is idempotency and how do you implement exactly-once processing?", "level": 2,
     "points": ["same operation multiple times same effect", "idempotency keys stored with results", "deduplication tables", "at-least-once delivery plus idempotent consumers", "transactional outbox"], "followups": []},
    {"q": "Explain the saga pattern for distributed transactions.", "level": 2,
     "points": ["sequence of local transactions", "compensating actions on failure", "choreography vs orchestration", "vs two-phase commit blocking issues", "eventual consistency"], "followups": []},
    {"q": "How do you handle failures between microservices?", "level": 2,
     "points": ["timeouts on every call", "retries with exponential backoff and jitter", "circuit breakers", "bulkheads", "fallbacks and graceful degradation", "idempotency for safe retries"], "followups": []},
    {"q": "What are vector clocks / Lamport timestamps?", "level": 3,
     "points": ["no global clock in distributed systems", "Lamport clocks give total order consistent with causality", "vector clocks detect concurrency", "conflict resolution", "hybrid logical clocks"], "followups": []},
    {"q": "Explain leader election and split brain.", "level": 2,
     "points": ["one node coordinates", "via ZooKeeper, etcd leases or Raft", "fencing tokens prevent stale leaders", "quorum requirement to avoid split brain"], "followups": []},
    {"q": "Strong vs eventual consistency — give examples.", "level": 1,
     "points": ["strong: read sees latest write, linearizability", "eventual: replicas converge", "read-your-writes and monotonic reads", "quorum settings", "use case examples"], "followups": []},
]

Q["data-eng"] = [
    {"q": "Explain Kafka's architecture: topics, partitions, brokers, consumer groups.", "level": 1,
     "points": ["topic split into partitions, ordered append-only logs", "partitions replicated across brokers with a leader and ISR", "producers choose partition by key", "consumer group: each partition read by one consumer in the group", "offsets committed per partition", "KRaft replaced ZooKeeper"], "followups": ["What happens during a rebalance?", "How many partitions should you choose?"]},
    {"q": "How does Kafka achieve exactly-once semantics?", "level": 3,
     "points": ["idempotent producer with producer ID and sequence numbers", "transactions across partitions", "read_committed isolation for consumers", "consume-transform-produce with offsets in the transaction", "external sinks need idempotency or two-phase commit"], "followups": []},
    {"q": "Explain event time vs processing time and watermarks in Flink.", "level": 2,
     "points": ["event time is when the event occurred", "processing time is when it's processed", "watermarks track event time progress", "bounded out-of-orderness", "late events: allowed lateness and side outputs", "windows fire when watermark passes window end"], "followups": ["What happens with an idle partition?"]},
    {"q": "How does Flink checkpointing provide fault tolerance?", "level": 3,
     "points": ["Chandy-Lamport style asynchronous barrier snapshots", "barriers flow with the stream", "barrier alignment for exactly-once", "unaligned checkpoints under backpressure", "state backends: heap vs RocksDB with incremental checkpoints", "savepoints for upgrades", "two-phase commit sinks"], "followups": ["Checkpoint vs savepoint?"]},
    {"q": "What is backpressure and how do streaming systems handle it?", "level": 2,
     "points": ["downstream slower than upstream", "Flink credit-based flow control", "Kafka consumers naturally pull", "scale parallelism, optimize operators", "monitoring backpressure metrics"], "followups": []},
    {"q": "Explain Spark's execution model: jobs, stages, tasks, shuffle.", "level": 2,
     "points": ["lazy transformations build a DAG", "actions trigger jobs", "stages split at shuffle boundaries", "tasks per partition", "narrow vs wide dependencies", "shuffle is expensive: disk and network", "Catalyst optimizer and Tungsten"], "followups": ["How do you handle data skew?"]},
    {"q": "How do you handle data skew in joins?", "level": 3,
     "points": ["identify hot keys", "broadcast join for small tables", "salting hot keys", "adaptive query execution skew join", "pre-aggregation"], "followups": []},
    {"q": "Lambda vs Kappa architecture.", "level": 2,
     "points": ["lambda: batch layer plus speed layer, two code paths", "kappa: single streaming pipeline with replay from log", "reprocessing by replaying Kafka", "trade-offs in complexity and correctness"], "followups": []},
    {"q": "Design a data warehouse model for an e-commerce company.", "level": 2,
     "points": ["star schema: fact tables for orders, dimensions for customer, product, date", "grain of the fact table", "slowly changing dimensions type 2", "partitioning and clustering", "ELT with dbt", "data quality checks"], "followups": ["What is SCD type 2?"]},
    {"q": "How do you ensure data quality in pipelines?", "level": 2,
     "points": ["schema validation and contracts with schema registry", "null, uniqueness, range checks", "freshness and volume monitoring", "dead-letter queues", "idempotent reprocessing", "lineage"], "followups": []},
    {"q": "Parquet vs Avro vs JSON — when do you use each?", "level": 1,
     "points": ["Parquet columnar, compression, analytics", "Avro row-based with schema evolution, good for Kafka", "JSON human readable but verbose", "predicate pushdown and column pruning"], "followups": []},
    {"q": "What is change data capture (CDC) and how would you implement it?", "level": 2,
     "points": ["capture row-level changes from database logs", "Debezium reading binlog or WAL into Kafka", "vs polling with timestamps", "ordering by primary key partition", "snapshot plus streaming", "outbox pattern"], "followups": []},
]

Q["java"] = [
    {"q": "How does HashMap work internally in Java?", "level": 2,
     "points": ["array of buckets indexed by hash", "hashCode spread and index by bit masking", "collisions chained in linked lists, treeified to red-black tree after 8", "resize at load factor 0.75 doubles capacity", "equals and hashCode contract", "not thread-safe, use ConcurrentHashMap"], "followups": ["How does ConcurrentHashMap achieve concurrency?"]},
    {"q": "Explain the JVM memory model and garbage collection.", "level": 2,
     "points": ["heap: young generation eden and survivor, old generation", "stack per thread, metaspace", "generational hypothesis", "minor vs major GC", "collectors: G1, ZGC, Shenandoah, Parallel", "GC tuning and pause times"], "followups": ["How would you debug a memory leak?"]},
    {"q": "What does volatile do and how is it different from synchronized?", "level": 2,
     "points": ["volatile guarantees visibility and ordering", "happens-before relationship", "no atomicity for compound actions", "synchronized gives mutual exclusion plus visibility", "atomic classes with CAS"], "followups": ["Explain double-checked locking."]},
    {"q": "Explain Java's ExecutorService and thread pools.", "level": 2,
     "points": ["reuse threads", "fixed, cached, scheduled, work stealing pools", "ThreadPoolExecutor core size, max size, queue, rejection policy", "Futures and CompletableFuture", "virtual threads in Java 21"], "followups": ["What are virtual threads and when do they help?"]},
    {"q": "What's new in modern Java (11-21) that you use?", "level": 1,
     "points": ["var local type inference", "records", "sealed classes", "pattern matching for instanceof and switch", "text blocks", "virtual threads", "streams improvements"], "followups": []},
    {"q": "equals and hashCode contract — why does it matter?", "level": 1,
     "points": ["equal objects must have equal hash codes", "used by hash-based collections", "breaking it loses entries in HashMap", "immutability of key fields"], "followups": []},
    {"q": "Checked vs unchecked exceptions?", "level": 1,
     "points": ["checked must be declared or handled", "unchecked RuntimeException subclasses", "when to use each", "try-with-resources"], "followups": []},
    {"q": "Explain Spring dependency injection and bean lifecycle.", "level": 2,
     "points": ["inversion of control container", "constructor injection preferred", "bean scopes singleton and prototype", "lifecycle: instantiate, populate, init callbacks, destroy", "proxies for AOP and transactions", "@Transactional pitfalls with self-invocation"], "followups": ["Why doesn't @Transactional work on a private method?"]},
    {"q": "How do Java streams work? Lazy evaluation?", "level": 1,
     "points": ["source, intermediate operations, terminal operation", "lazy intermediate operations", "short-circuiting", "parallel streams use ForkJoinPool", "avoid side effects"], "followups": []},
    {"q": "String vs StringBuilder vs StringBuffer; why is String immutable?", "level": 1,
     "points": ["String immutable, string pool", "security, caching hash codes, thread safety", "StringBuilder mutable non-synchronized", "StringBuffer synchronized"], "followups": []},
]

Q["python"] = [
    {"q": "Explain the GIL and its implications.", "level": 2,
     "points": ["global interpreter lock allows one thread to execute bytecode", "limits CPU-bound threading", "I/O-bound threads still benefit", "multiprocessing for CPU-bound", "asyncio for concurrency", "free-threaded Python 3.13 experiment"], "followups": []},
    {"q": "What are generators and why use them?", "level": 1,
     "points": ["functions using yield", "lazy evaluation and memory efficiency", "iterator protocol", "generator expressions", "yield from"], "followups": []},
    {"q": "Explain decorators with an example.", "level": 1,
     "points": ["function taking a function returning a function", "closures", "functools.wraps", "use cases: logging, caching, auth", "decorators with arguments"], "followups": []},
    {"q": "Mutable default arguments — what's the pitfall?", "level": 1,
     "points": ["default evaluated once at definition", "shared list across calls", "use None and create inside"], "followups": []},
    {"q": "How does asyncio work?", "level": 2,
     "points": ["event loop", "coroutines with async and await", "cooperative multitasking", "non-blocking I/O", "gather and tasks", "don't block the loop with CPU work"], "followups": []},
    {"q": "List vs tuple vs set vs dict — complexities and use cases.", "level": 1,
     "points": ["list ordered mutable, O(1) append, O(n) search", "tuple immutable, hashable", "set O(1) membership", "dict hash map O(1) average", "ordering guarantees of dict"], "followups": []},
]

Q["cloud"] = [
    {"q": "Explain how Kubernetes schedules and runs your application.", "level": 2,
     "points": ["pods, deployments, replica sets, services", "control plane: API server, etcd, scheduler, controller manager", "kubelet on nodes", "scheduler uses resource requests and affinity", "liveness and readiness probes", "rolling updates"], "followups": ["Difference between liveness and readiness probes?"]},
    {"q": "Docker containers vs virtual machines.", "level": 1,
     "points": ["containers share host kernel", "namespaces and cgroups", "lighter and faster startup", "VMs have full guest OS and stronger isolation", "image layers"], "followups": []},
    {"q": "How would you design a CI/CD pipeline?", "level": 2,
     "points": ["build, test, static analysis, security scan", "artifact versioning", "deploy to staging, integration tests", "progressive delivery: canary or blue-green", "automated rollback on metrics", "infrastructure as code"], "followups": ["Canary vs blue-green?"]},
    {"q": "How do you make a service highly available on AWS?", "level": 2,
     "points": ["multiple availability zones", "load balancer and auto-scaling groups", "managed multi-AZ databases", "health checks", "stateless services", "backups and disaster recovery RTO RPO"], "followups": []},
    {"q": "What are the golden signals / how do you approach observability?", "level": 1,
     "points": ["latency, traffic, errors, saturation", "metrics, logs, traces", "SLIs, SLOs, error budgets", "alert on symptoms not causes", "distributed tracing with OpenTelemetry"], "followups": []},
    {"q": "Horizontal vs vertical scaling?", "level": 1,
     "points": ["vertical: bigger machine, simple, limits", "horizontal: more machines, needs statelessness and load balancing", "cost and resilience", "auto-scaling"], "followups": []},
]

Q["frontend"] = [
    {"q": "Explain the JavaScript event loop.", "level": 2,
     "points": ["single-threaded call stack", "web APIs handle async work", "task queue and microtask queue", "microtasks (promises) run before next macrotask", "rendering between tasks"], "followups": ["Order of setTimeout vs Promise.then?"]},
    {"q": "What are closures?", "level": 1,
     "points": ["function remembers its lexical scope", "data privacy", "classic loop var pitfall", "memory implications"], "followups": []},
    {"q": "How does React rendering and reconciliation work?", "level": 2,
     "points": ["virtual DOM diffing", "keys for lists", "state changes trigger re-render", "memoization with React.memo, useMemo, useCallback", "concurrent rendering"], "followups": []},
    {"q": "How would you improve web page performance?", "level": 2,
     "points": ["measure with Core Web Vitals", "reduce bundle size, code splitting", "lazy loading images", "caching and CDN", "avoid layout thrashing", "server-side rendering"], "followups": []},
    {"q": "Explain CORS.", "level": 1,
     "points": ["same-origin policy", "server sends Access-Control-Allow-Origin", "preflight OPTIONS requests", "credentials handling"], "followups": []},
]

Q["ml"] = [
    {"q": "Design a retrieval-augmented generation (RAG) system for company documents.", "level": 3,
     "points": ["ingest and chunk documents", "embeddings and vector database", "hybrid search with keyword BM25", "reranking", "prompt with retrieved context and citations", "evaluation of retrieval and answer quality", "access control and freshness"], "followups": ["How do you evaluate a RAG system?"]},
    {"q": "Explain bias-variance trade-off.", "level": 1,
     "points": ["bias: underfitting from simple models", "variance: overfitting sensitive to training data", "regularization, more data, ensembles", "cross-validation"], "followups": []},
    {"q": "Design a recommendation system.", "level": 3,
     "points": ["candidate generation then ranking", "collaborative filtering and embeddings", "content-based features", "cold start problem", "online metrics and A/B testing", "feature store and serving latency"], "followups": []},
    {"q": "Precision vs recall — when do you optimize which?", "level": 1,
     "points": ["precision: of predicted positives how many correct", "recall: of actual positives how many found", "F1 score", "fraud and medical favor recall, spam favors precision", "threshold tuning"], "followups": []},
    {"q": "How do transformers / attention work at a high level?", "level": 2,
     "points": ["self-attention with queries, keys, values", "scaled dot product", "multi-head attention", "positional encoding", "parallelizable unlike RNNs", "quadratic cost in sequence length"], "followups": []},
]

SD_PHASES = [
    ("Requirements", "Clarify functional & non-functional requirements. What's in scope? Scale? Latency/availability/consistency targets?"),
    ("Estimation", "Back-of-envelope: DAU, read/write QPS (avg & peak), storage per year, bandwidth."),
    ("API", "Define the core API endpoints with request/response shapes."),
    ("High-level design", "Draw the main components: clients, LB, services, caches, databases, queues. Walk a request through it."),
    ("Data model", "Schemas, choice of database(s), partition/shard key, indexes."),
    ("Deep dive", "Pick the 1-2 hardest parts and go deep (e.g. fan-out, consistency, hot keys)."),
    ("Bottlenecks & trade-offs", "Single points of failure, failure modes, scaling limits, what you'd monitor, how it degrades."),
]
