# -*- coding: utf-8 -*-
"""Multiple-choice question bank. Each: (question, [options], index_of_correct, why).
Subjects match the Learn hub subjects so accuracy feeds Weak Topics / Analytics."""

SUBJECTS = {
    "dsa": "DSA", "java": "Java", "spring": "Spring Boot", "databases": "Databases & SQL", "kafka": "Kafka",
    "microservices": "Microservices", "system-design": "System Design", "kubernetes": "Kubernetes",
    "cloud": "Cloud", "networking": "Networking", "devops": "DevOps", "os": "OS & Concurrency",
    "python": "Python", "security": "Security",
}

_RAW = {
    "dsa": [
        ("What is the time complexity of searching a balanced BST with n nodes?", ["O(1)", "O(log n)", "O(n)", "O(n log n)"], 1, "Each comparison halves the remaining height; a balanced tree has height ~log n."),
        ("Which data structure gives O(1) average insert and lookup by key?", ["Sorted array", "Binary heap", "Hash map", "Linked list"], 2, "Hash maps hash the key directly to a bucket."),
        ("Best approach for 'longest substring without repeating characters'?", ["Sort + scan", "Sliding window with a set/map", "DP on all substrings", "Binary search"], 1, "Expand right, shrink left when a duplicate enters — O(n)."),
        ("Which algorithm finds shortest paths in a graph with non-negative weights?", ["DFS", "Dijkstra", "Kruskal", "Topological sort"], 1, "Dijkstra with a min-heap: O((V+E) log V). Negative weights need Bellman-Ford."),
        ("Top-K most frequent elements efficiently?", ["Sort all: O(n log n) only", "Min-heap of size k: O(n log k)", "Max-heap of all elements then pop n times", "Binary search"], 1, "Keep the k best in a min-heap; bucket sort gives O(n)."),
        ("Detect a cycle in a linked list with O(1) extra space:", ["Hash set of nodes", "Fast & slow pointers", "Recursion", "Sort the nodes"], 1, "Floyd's tortoise and hare — they meet inside the cycle."),
        ("Which traversal of a BST yields sorted order?", ["Pre-order", "In-order", "Post-order", "Level-order"], 1, "Left, node, right visits keys ascending."),
        ("Course Schedule (can all courses be finished?) is solved by:", ["Union-Find", "Topological sort / cycle detection", "Dijkstra", "Binary search"], 1, "Prerequisites form a directed graph; a cycle makes it impossible."),
        ("Number of Islands is most naturally solved with:", ["Dynamic programming", "BFS/DFS flood fill", "Two pointers", "Heap"], 1, "Each unvisited land cell starts a flood fill; count starts."),
        ("0/1 knapsack with capacity W and n items runs in:", ["O(2^n) only", "O(n·W) with DP", "O(n log n)", "O(W)"], 1, "dp[w] over items, iterating w downward: pseudo-polynomial O(nW)."),
        ("Monotonic stack is the go-to for:", ["Next greater element", "Shortest path", "Median of stream", "Anagram grouping"], 0, "Pop smaller elements when a bigger one arrives — each element pushed/popped once."),
        ("Median of a data stream uses:", ["One min-heap", "Two heaps (max-heap low half, min-heap high half)", "Sorted linked list", "Trie"], 1, "Balanced heaps give O(log n) insert, O(1) median."),
        ("Union-Find with path compression + union by rank has amortized cost per op:", ["O(log n)", "O(α(n)) — nearly constant", "O(n)", "O(1) worst case"], 1, "Inverse Ackermann; effectively ≤ 4."),
        ("Binary search 'on the answer' applies when:", ["Input is sorted", "Feasibility is monotonic in the answer", "Graph is a DAG", "Array has duplicates"], 1, "If x works then every bigger x works → binary search the smallest feasible x (e.g. Koko Eating Bananas)."),
        ("Merge Intervals first requires:", ["Sort by start", "Sort by end descending", "A hash map", "A heap of ends only"], 0, "After sorting by start, overlapping intervals are adjacent."),
        ("Space complexity of recursive DFS on a tree of height h:", ["O(1)", "O(h)", "O(n²)", "O(log h)"], 1, "The call stack holds one frame per level."),
    ],
    "java": [
        ("What happens if you override equals() but not hashCode()?", ["Compile error", "HashMap/HashSet may treat equal objects as different", "Nothing", "Runtime exception"], 1, "Equal objects must have equal hash codes or they land in different buckets."),
        ("HashMap in Java 8+ turns a bucket's list into a tree when:", ["Always", "The bucket exceeds 8 entries (and table ≥ 64)", "Load factor exceeds 0.75", "Keys are Comparable"], 1, "Treeification bounds worst-case lookup to O(log n)."),
        ("Which is thread-safe AND allows concurrent reads without locking the whole map?", ["Hashtable", "Collections.synchronizedMap", "ConcurrentHashMap", "TreeMap"], 2, "CHM uses CAS + per-bin locking; reads are lock-free."),
        ("What does 'volatile' guarantee?", ["Atomicity of i++", "Visibility and ordering of reads/writes", "Mutual exclusion", "Deadlock freedom"], 1, "volatile establishes happens-before; count++ is still not atomic."),
        ("String s = \"a\" + \"b\"; creates:", ["Two objects at runtime", "A compile-time constant \"ab\" from the pool", "A StringBuilder always", "A char[] only"], 1, "Constant expressions are folded by the compiler."),
        ("Which GC is the default in modern JDKs (11+) for server-class machines?", ["Serial", "Parallel", "G1", "CMS"], 2, "G1 is default since JDK 9; ZGC/Shenandoah are opt-in low-pause collectors."),
        ("OutOfMemoryError: Metaspace usually indicates:", ["Too many threads", "Class metadata growth / classloader leak", "Heap too small for objects", "Stack overflow"], 1, "Metaspace holds class metadata; leaking classloaders (redeploys, dynamic proxies) fill it."),
        ("Optional should primarily be used as:", ["Field type in entities", "Method return type for maybe-absent values", "Method parameter", "Collection element"], 1, "It's designed for return values; avoid in fields/params."),
        ("Which stream operation is terminal?", ["map", "filter", "collect", "peek"], 2, "Terminal ops (collect, forEach, reduce) trigger execution; intermediate ops are lazy."),
        ("Virtual threads (Java 21) are best for:", ["CPU-bound number crunching", "Many concurrent blocking I/O tasks", "Replacing all synchronization", "GPU work"], 1, "They make blocking cheap; CPU-bound work still needs cores."),
        ("A checked exception must be:", ["Ignored", "Caught or declared with throws", "A subclass of RuntimeException", "Logged"], 1, "The compiler enforces handling of checked exceptions."),
        ("ArrayList vs LinkedList: random access get(i) is:", ["O(1) vs O(n)", "O(n) vs O(1)", "Both O(1)", "Both O(log n)"], 0, "ArrayList is array-backed; LinkedList must walk nodes."),
        ("What does the 'final' keyword on a reference variable mean?", ["Object is immutable", "Reference can't be reassigned", "Class can't be loaded", "Method is static"], 1, "The referenced object's state can still change."),
        ("ExecutorService.shutdown() does what?", ["Kills running tasks", "Stops accepting new tasks, lets queued ones finish", "Blocks until done", "Clears the queue"], 1, "shutdownNow() interrupts; awaitTermination() waits."),
        ("CompletableFuture.thenCompose is used to:", ["Run two futures in parallel", "Chain a function that itself returns a CompletableFuture (flatMap)", "Handle exceptions", "Block for result"], 1, "thenApply maps; thenCompose flattens nested futures."),
    ],
    "spring": [
        ("@SpringBootApplication combines:", ["@Configuration, @EnableAutoConfiguration, @ComponentScan", "@Component, @Service, @Repository", "@RestController, @RequestMapping", "@EnableWebMvc, @Bean"], 0, "Those three annotations are the meta-annotations."),
        ("Why does @Transactional on a method called from the same class not start a transaction?", ["It's private", "Self-invocation bypasses the Spring proxy", "Transactions need XML", "Only works on interfaces"], 1, "The proxy only intercepts calls coming from outside the bean."),
        ("By default @Transactional rolls back on:", ["Any exception", "RuntimeException and Error", "Checked exceptions only", "Nothing"], 1, "Use rollbackFor = Exception.class to include checked exceptions."),
        ("REQUIRES_NEW propagation:", ["Joins the existing transaction", "Suspends the outer transaction and starts a new one", "Throws if a transaction exists", "Creates a savepoint"], 1, "Commits independently — useful for audit logs."),
        ("How do you override an auto-configured bean?", ["Edit the starter jar", "Define your own bean of that type (@ConditionalOnMissingBean backs off)", "Use @Primary on the starter", "It's impossible"], 1, "Auto-config classes back off when a user bean exists."),
        ("Default bean scope in Spring is:", ["prototype", "request", "singleton", "session"], 2, "One instance per container."),
        ("Which slice test loads only the web layer with MockMvc?", ["@SpringBootTest", "@WebMvcTest", "@DataJpaTest", "@JsonTest"], 1, "Controllers, advice, filters and MockMvc — services must be mocked."),
        ("The N+1 problem in JPA is typically fixed with:", ["More indexes", "JOIN FETCH / @EntityGraph / batch fetching", "EAGER on every relation", "Second-level cache only"], 1, "Fetch what the use case needs in one query."),
        ("spring.jpa.open-in-view should usually be:", ["true for performance", "false, to avoid lazy loading during view rendering and long-held connections", "irrelevant", "true for REST APIs"], 1, "OSIV keeps the session open for the whole request."),
        ("Constructor injection is preferred because:", ["It's shorter", "Dependencies are explicit, immutable and testable without Spring", "Field injection is removed", "It's faster at runtime"], 1, "Also fails fast on missing dependencies."),
        ("Which Actuator endpoint should Kubernetes readiness probes target?", ["/actuator/env", "/actuator/health/readiness", "/actuator/beans", "/actuator/heapdump"], 1, "Enable probes with management.endpoint.health.probes.enabled."),
        ("@ControllerAdvice is used for:", ["Scheduling tasks", "Global exception handling / binding across controllers", "Security filters", "Caching"], 1, "With @ExceptionHandler methods returning ProblemDetail etc."),
        ("Configuration precedence: which wins?", ["application.yml", "Environment variable", "Default in @Value", "application-dev.yml when prod is active"], 1, "Command-line args > env vars > profile yml > application.yml."),
        ("@Transactional(readOnly = true) mainly:", ["Blocks writes at DB level always", "Hints optimizations like skipping dirty checking/flush", "Enables caching", "Makes queries parallel"], 1, "Some drivers also route to replicas."),
    ],
    "databases": [
        ("Which isolation level prevents dirty reads but allows non-repeatable reads?", ["Read Uncommitted", "Read Committed", "Repeatable Read", "Serializable"], 1, "RC only sees committed data but a re-read can see new commits."),
        ("A composite index on (a, b) helps which query most?", ["WHERE b = ?", "WHERE a = ? AND b = ?", "WHERE a LIKE '%x'", "ORDER BY b"], 1, "Leftmost-prefix rule: (a) or (a, b) predicates."),
        ("Difference between WHERE and HAVING:", ["None", "WHERE filters rows before grouping, HAVING filters groups after", "HAVING is faster", "WHERE only works with joins"], 1, "HAVING can reference aggregates."),
        ("MVCC lets readers:", ["Block writers", "See a consistent snapshot without blocking writers", "Skip indexes", "Avoid WAL"], 1, "Each transaction sees versions valid at its snapshot."),
        ("Which join returns all rows from the left table even without matches?", ["INNER JOIN", "LEFT JOIN", "CROSS JOIN", "SEMI JOIN"], 1, "Unmatched right columns are NULL."),
        ("ROW_NUMBER() vs RANK() on ties:", ["Identical", "ROW_NUMBER gives unique numbers; RANK gives ties the same rank and leaves gaps", "RANK is unique", "Both leave gaps"], 1, "DENSE_RANK gives ties the same rank without gaps."),
        ("Why can an index make writes slower?", ["It can't", "Every insert/update must also update each index", "Indexes lock tables", "Indexes disable WAL"], 1, "Write amplification — index only what queries need."),
        ("A covering index means:", ["Index on every column", "The index contains all columns a query needs (index-only scan)", "A clustered primary key", "A partial index"], 1, "No table lookups needed."),
        ("Best practice for pagination over huge tables:", ["OFFSET 1000000", "Keyset/seek pagination (WHERE id > last_id ORDER BY id LIMIT n)", "SELECT * then slice in app", "Random sampling"], 1, "OFFSET scans and discards rows."),
        ("In Redis, a sorted set is ideal for:", ["Leaderboards", "Blob storage", "Full-text search", "Joins"], 0, "ZADD/ZRANGE by score in O(log n)."),
        ("LSM-tree storage engines (Cassandra, RocksDB) optimize for:", ["Random reads", "High write throughput", "Joins", "Small datasets"], 1, "Sequential writes to memtable/SSTables; compaction later."),
        ("What does EXPLAIN ANALYZE show?", ["Schema", "The actual executed plan with row counts and timings", "Only estimated cost", "Index definitions"], 1, "Compare estimates vs actuals to spot bad statistics."),
        ("Write skew is prevented by:", ["Read Committed", "Serializable isolation (or explicit locking)", "Indexes", "Replication"], 1, "Two txns read overlapping data and write disjoint rows — classic on-call doctors example."),
        ("Normalization to 3NF removes:", ["All joins", "Transitive dependencies on non-key attributes", "Primary keys", "Indexes"], 1, "Every non-key attribute depends on the key, the whole key and nothing but the key."),
    ],
    "kafka": [
        ("Ordering in Kafka is guaranteed:", ["Across the whole topic", "Within a partition", "Across consumer groups", "Never"], 1, "Use a key so related events land in the same partition."),
        ("Max useful consumers in one group for a topic with 12 partitions:", ["Unlimited", "12", "24", "1"], 1, "Each partition goes to one consumer per group; extras sit idle."),
        ("acks=all means the leader waits for:", ["Nothing", "Itself only", "All in-sync replicas", "All brokers in the cluster"], 2, "Combine with min.insync.replicas=2 for durability."),
        ("Enabling idempotent producers prevents:", ["Consumer duplicates", "Duplicates from producer retries within a partition", "Rebalances", "Data loss on disk failure"], 1, "Producer ID + sequence numbers let brokers drop duplicates."),
        ("Exactly-once processing in Kafka Streams / read-process-write relies on:", ["acks=0", "Transactions + read_committed consumers", "Compaction", "Larger batches"], 1, "Offsets and output written atomically in a transaction."),
        ("Log compaction keeps:", ["Only the first message per key", "The latest value per key", "Messages for 7 days", "Only tombstones"], 1, "Great for changelog/state topics."),
        ("Consumer lag is:", ["Network latency", "Latest offset minus committed offset", "Number of partitions", "Rebalance time"], 1, "The key health metric for consumers."),
        ("Committing offsets BEFORE processing gives:", ["At-least-once", "At-most-once", "Exactly-once", "No delivery"], 1, "A crash after commit but before processing loses the message."),
        ("What triggers a consumer group rebalance?", ["A message is produced", "A consumer joins/leaves or exceeds max.poll.interval.ms", "Compaction", "A topic config read"], 1, "Cooperative sticky assignment reduces the disruption."),
        ("A poison message that always fails should go to:", ["Retry forever", "A dead-letter topic after N attempts", "Be dropped silently", "A different partition"], 1, "Keeps the partition moving; alert on DLT volume."),
        ("Increasing partitions for a keyed topic can:", ["Never cause issues", "Break key → partition mapping (ordering for existing keys)", "Delete data", "Reduce throughput"], 1, "hash(key) % partitions changes."),
        ("ISR stands for:", ["In-Sync Replicas", "Internal Stream Router", "Indexed Segment Record", "Idempotent Send Retry"], 0, "Replicas caught up with the leader within replica.lag.time.max.ms."),
    ],
    "microservices": [
        ("Which pattern keeps DB writes and event publishing consistent?", ["Two-phase commit via HTTP", "Transactional outbox", "Shared database", "Cron job"], 1, "Write the event to an outbox table in the same transaction; relay publishes it."),
        ("A saga handles:", ["Caching", "Distributed business transactions with compensating actions", "Service discovery", "Load balancing"], 1, "Orchestrated or choreographed local transactions."),
        ("A circuit breaker in OPEN state:", ["Sends all calls", "Fails fast without calling the dependency", "Retries forever", "Queues calls"], 1, "After a wait it goes HALF_OPEN to probe."),
        ("Database per service means:", ["Each service has its own DB server", "No other service accesses a service's data store directly", "No SQL allowed", "Shared schemas"], 1, "Logical ownership; data shared via APIs/events."),
        ("BFF stands for:", ["Backend For Frontend", "Big Fat Framework", "Binary File Format", "Batch Fetch Filter"], 0, "A tailored API layer per client type."),
        ("Consumer-driven contract testing (Pact) mainly replaces:", ["Unit tests", "Many cross-service end-to-end integration tests", "Load tests", "Security scans"], 1, "Verifies provider against consumer expectations in CI."),
        ("Availability of a sync chain of 4 services each 99.9%:", ["99.9%", "≈99.6%", "99.99%", "≈96%"], 1, "0.999^4 ≈ 0.996."),
        ("Bulkhead pattern:", ["Retries with jitter", "Isolates resources (pools) per dependency so one can't exhaust all", "Encrypts traffic", "Caches responses"], 1, "Like ship compartments."),
        ("Strangler fig pattern is used for:", ["Load testing", "Incrementally replacing a legacy system", "Caching", "Security"], 1, "Route slices of traffic to new services until the old one is gone."),
        ("A distributed monolith is characterized by:", ["Independent deploys", "Services that must be deployed together / share a DB / chatty sync calls", "One repo", "Using Kubernetes"], 1, "All the costs, none of the independence."),
        ("Idempotency key on POST /payments ensures:", ["Faster responses", "Retried requests don't create duplicate charges", "Encryption", "Rate limiting"], 1, "Server stores key → result and replays it."),
        ("Service mesh sidecars typically provide:", ["Business logic", "mTLS, retries, timeouts, traffic splitting, telemetry", "Database migrations", "UI rendering"], 1, "Envoy/Linkerd proxies next to each pod."),
    ],
    "system-design": [
        ("Consistent hashing is used to:", ["Encrypt data", "Minimize key movement when nodes join/leave", "Sort data", "Compress data"], 1, "Only ~K/N keys move; virtual nodes smooth distribution."),
        ("Cache-aside means:", ["Cache writes to DB", "App reads cache, on miss reads DB and populates cache", "DB pushes to cache", "No TTLs"], 1, "Most common pattern; invalidate on write."),
        ("Thundering herd / cache stampede mitigation:", ["Lower TTL", "Request coalescing / locks, jittered TTLs, early refresh", "More DB replicas only", "Disable cache"], 1, "Only one request rebuilds a hot key."),
        ("CAP theorem: during a network partition you must choose between:", ["Latency and throughput", "Consistency and availability", "Durability and speed", "SQL and NoSQL"], 1, "PACELC adds the latency/consistency trade-off when there is no partition."),
        ("For a URL shortener, a good ID strategy is:", ["Random UUID in URL", "Base62 of a unique counter / pre-generated key range", "MD5 of URL truncated without collision check", "Timestamp only"], 1, "Short, unique, collision-free."),
        ("Fan-out on write for a news feed is problematic for:", ["Users with few followers", "Celebrities with millions of followers", "Read-heavy systems", "Small systems"], 1, "Use hybrid: pull celebrity posts at read time."),
        ("A token bucket rate limiter allows:", ["No bursts", "Bursts up to bucket size, average rate = refill rate", "Only fixed windows", "Unlimited requests"], 1, "Tokens refill at rate r up to capacity b."),
        ("Read replicas help with:", ["Write scalability", "Read scalability (with replication lag)", "Strong consistency", "Schema changes"], 1, "Route read-your-writes to the primary if needed."),
        ("~How many seconds in a day (for QPS estimates)?", ["~8,600", "~86,400 (≈10^5)", "~864,000", "~3,600"], 1, "1M requests/day ≈ 12 QPS average."),
        ("Which store fits time-series metrics best?", ["Graph DB", "Time-series DB (Prometheus/Influx/Timescale) or wide-column", "Document DB only", "Blob storage"], 1, "Append-heavy, time-range queries, downsampling."),
        ("Geohash / quadtree are used for:", ["Text search", "Proximity (nearby drivers/places) queries", "Caching", "Auth"], 1, "Map 2D location to indexable cells."),
        ("A CDN primarily reduces:", ["DB writes", "Latency and origin load for cacheable content", "CPU on clients", "Consistency"], 1, "Edge caches near users."),
        ("Write-ahead log (WAL) provides:", ["Faster reads", "Durability & crash recovery", "Compression", "Sharding"], 1, "Log first, apply later, replay on crash."),
        ("Leader election in distributed systems is typically done via:", ["Random choice", "Consensus (Raft/ZooKeeper/etcd leases)", "Round robin DNS", "Cron"], 1, "Leases with fencing tokens prevent split brain."),
    ],
    "kubernetes": [
        ("The smallest deployable unit in Kubernetes is:", ["Container", "Pod", "Node", "Deployment"], 1, "One or more containers sharing network and volumes."),
        ("A failing liveness probe causes:", ["Pod removed from Service endpoints", "Container restart", "Node drain", "Nothing"], 1, "Readiness failure removes it from endpoints instead."),
        ("CrashLoopBackOff usually means:", ["Image not found", "Container starts and exits/crashes repeatedly", "Node out of disk", "Service misconfigured"], 1, "Check kubectl logs --previous and describe."),
        ("OOMKilled means:", ["CPU throttled", "Container exceeded its memory limit", "Disk full", "Evicted by scheduler"], 1, "Raise limit or fix memory usage (JVM: MaxRAMPercentage)."),
        ("Which object gives pods stable network identity and storage per replica?", ["Deployment", "StatefulSet", "DaemonSet", "Job"], 1, "Stable names (db-0, db-1) and PVC per pod."),
        ("DaemonSet runs:", ["One pod per node", "N replicas anywhere", "Once to completion", "On a schedule"], 0, "Log shippers, node exporters, CNI agents."),
        ("Service type ClusterIP exposes a service:", ["To the internet", "Only inside the cluster", "Via node ports", "Via DNS only outside"], 1, "Use Ingress/LoadBalancer for external traffic."),
        ("HPA scales based on:", ["Node count", "Metrics like CPU/memory/custom per pod", "Image size", "Git commits"], 1, "Horizontal Pod Autoscaler adjusts replicas."),
        ("CPU limits cause what when exceeded?", ["OOMKill", "Throttling", "Eviction immediately", "Restart"], 1, "CPU is compressible; memory is not."),
        ("A PodDisruptionBudget protects against:", ["Crashes", "Too many voluntary disruptions (drains/upgrades) at once", "Network partitions", "Image pulls"], 1, "minAvailable / maxUnavailable."),
        ("Secrets in Kubernetes are by default:", ["Strongly encrypted", "Base64-encoded (enable encryption at rest / external secret stores)", "Hashed", "Not stored"], 1, "Treat RBAC to secrets carefully."),
        ("Rolling update with maxUnavailable=0, maxSurge=1 means:", ["Downtime", "New pod starts before an old one is removed", "All pods replaced at once", "Blue-green"], 1, "Zero capacity loss during rollout."),
    ],
    "cloud": [
        ("S3 is best described as:", ["Block storage", "Object storage", "File system only", "Database"], 1, "Durable key → object store with 11 nines durability."),
        ("To let private-subnet instances reach the internet you use:", ["Internet gateway directly", "NAT gateway", "VPC peering", "Security group"], 1, "Outbound only; IGW is for public subnets."),
        ("Security groups are:", ["Stateless", "Stateful instance-level firewalls", "Subnet-level only", "DNS rules"], 1, "NACLs are stateless and subnet-level."),
        ("Multi-AZ deployment protects against:", ["Region outage", "Single data-center (AZ) failure", "Bad deploys", "DDoS"], 1, "Multi-region for regional failures."),
        ("Least-privilege IAM means:", ["Admin for everyone", "Grant only permissions needed for the task", "No IAM", "Root keys in CI"], 1, "Use roles, not long-lived keys."),
        ("Serverless functions (Lambda) are a poor fit for:", ["Spiky event handlers", "Long-running, steady high-throughput or latency-critical cold-start-sensitive workloads", "Glue code", "Cron jobs"], 1, "Cost and cold starts at steady high load."),
        ("SQS standard queues guarantee:", ["Exactly-once, ordered", "At-least-once, best-effort ordering", "At-most-once", "Strict FIFO"], 1, "FIFO queues give ordering + dedup with lower throughput."),
        ("RPO means:", ["Max acceptable downtime", "Max acceptable data loss window", "Response time", "Replica count"], 1, "RTO = time to restore."),
        ("Infrastructure as Code tools include:", ["Terraform, CloudFormation, Pulumi", "Jenkins only", "Grafana", "Kafka"], 0, "Declarative, reviewed, versioned infrastructure."),
        ("Cheapest compute for fault-tolerant batch jobs:", ["On-demand", "Spot/preemptible instances", "Dedicated hosts", "Reserved for 1 hour"], 1, "Can be reclaimed — design for interruption."),
    ],
    "networking": [
        ("How many addresses in a /24?", ["24", "256", "1024", "65536"], 1, "2^(32−24) = 256."),
        ("TCP 3-way handshake is:", ["SYN, ACK, FIN", "SYN, SYN-ACK, ACK", "HELLO, KEY, DONE", "ACK, SYN, ACK"], 1, "One RTT before data."),
        ("'Connection refused' typically means:", ["Firewall drop", "Host reachable but nothing listening on the port", "DNS failure", "TLS error"], 1, "Timeouts suggest firewall/routing drops."),
        ("HTTP/2's main improvement over HTTP/1.1:", ["Text protocol", "Multiplexing many streams over one connection", "UDP transport", "No headers"], 1, "Plus header compression (HPACK)."),
        ("QUIC runs over:", ["TCP", "UDP", "ICMP", "SCTP"], 1, "HTTP/3 = HTTP over QUIC."),
        ("A 504 Gateway Timeout means:", ["Client sent a bad request", "A proxy didn't get a timely response from upstream", "Auth failed", "Not found"], 1, "502 = bad/invalid upstream response."),
        ("DNS CNAME records cannot be used at:", ["Subdomains", "The zone apex (example.com)", "www", "Any record"], 1, "Use ALIAS/ANAME or A records at the apex."),
        ("L7 load balancers can route by:", ["IP only", "HTTP path, host, headers", "MAC address", "Nothing"], 1, "L4 routes by IP/port."),
        ("Many sockets in CLOSE_WAIT indicate:", ["Normal load", "The application isn't closing connections (leak)", "SYN flood", "DNS issues"], 1, "Remote closed; local app never called close()."),
        ("TLS 1.3 full handshake costs:", ["0 RTT", "1 RTT", "2 RTT", "3 RTT"], 1, "0-RTT only on resumption and is replayable."),
        ("Which is idempotent?", ["POST", "PUT", "PATCH (always)", "None"], 1, "GET, PUT, DELETE are idempotent by spec."),
        ("NAT allows:", ["Encryption", "Many private hosts to share a public IP", "DNS resolution", "Routing between VLANs only"], 1, "Port address translation maps connections."),
    ],
    "devops": [
        ("Blue-green deployment means:", ["Deploy to 5% then 100%", "Two identical environments; switch traffic at once, instant rollback", "Rolling pod by pod", "Deploy only at night"], 1, "Canary is the gradual one."),
        ("DORA metrics include:", ["Lines of code", "Deployment frequency, lead time, change failure rate, time to restore", "Story points", "Test count"], 1, "Measures delivery performance."),
        ("A Dockerfile best practice:", ["One huge layer", "Multi-stage builds, small base, non-root user, pin versions", "Run as root", "Copy secrets into image"], 1, "Also order layers for cache efficiency."),
        ("GitOps means:", ["Using git for code only", "Desired infra/app state in git, reconciled automatically by an agent (Argo CD/Flux)", "Manual kubectl", "Pushing to main"], 1, "Pull-based deployments with audit trail."),
        ("An SLO is:", ["A contract with penalties", "An internal target for a reliability SLI (e.g. 99.9% of requests < 300ms)", "A log format", "A deployment tool"], 1, "SLA is the external contract."),
        ("An error budget of 99.9% monthly availability ≈:", ["4.3 minutes", "43 minutes", "7.2 hours", "0"], 1, "0.1% of ~43,200 minutes."),
        ("Terraform state stores:", ["Source code", "Mapping between config and real resources", "Logs", "Secrets only"], 1, "Keep it remote, locked and encrypted."),
        ("Feature flags let you:", ["Skip tests", "Decouple deploy from release and roll back features instantly", "Avoid code review", "Scale DBs"], 1, "Clean them up afterwards."),
        ("The three pillars of observability:", ["CPU, memory, disk", "Metrics, logs, traces", "Dev, QA, prod", "Alerts, pages, tickets"], 1, "Plus profiles/events increasingly."),
        ("Alerting best practice:", ["Alert on every CPU spike", "Alert on user-facing symptoms (SLO burn), with runbooks", "Email only", "No alerts"], 1, "Page on symptoms, investigate causes."),
    ],
    "os": [
        ("Processes vs threads:", ["Threads have separate address spaces", "Threads share the process address space; processes are isolated", "Identical", "Processes are lighter"], 1, "Context switching threads is cheaper."),
        ("The four Coffman deadlock conditions:", ["Mutual exclusion, hold and wait, no preemption, circular wait", "Starvation, livelock, race, deadlock", "Locks, semaphores, monitors, CAS", "None"], 0, "Break any one to prevent deadlock."),
        ("A race condition happens when:", ["Code is slow", "Outcome depends on unsynchronized interleaving of shared-state access", "Two processes run", "Using threads always"], 1, "Protect critical sections."),
        ("Virtual memory provides:", ["Faster CPU", "Each process an isolated address space mapped to physical pages", "More disk", "Networking"], 1, "Page tables + TLB; paging to disk."),
        ("A semaphore with count 1 behaves like:", ["A condition variable", "A mutex (binary semaphore)", "A barrier", "A spinlock always"], 1, "Counting semaphores limit concurrency to N."),
        ("Context switch cost comes from:", ["Nothing", "Saving/restoring registers, scheduler work, cache/TLB pollution", "Disk I/O", "Network"], 1, "Why too many threads hurt throughput."),
        ("Thrashing is:", ["High CPU use", "Excessive paging leaving little useful work", "Deadlock", "Network congestion"], 1, "Working set exceeds RAM."),
        ("Which avoids lost updates on a shared counter across threads in Java?", ["int++", "AtomicInteger.incrementAndGet or LongAdder", "volatile int++", "static int"], 1, "CAS-based atomics."),
    ],
    "python": [
        ("The GIL means:", ["No threads in Python", "Only one thread executes Python bytecode at a time per interpreter (CPython)", "Processes share memory", "Async is disabled"], 1, "Use multiprocessing for CPU-bound; threads/async fine for I/O."),
        ("Mutable default argument def f(x=[]):", ["New list each call", "Same list shared across calls", "Syntax error", "Tuple"], 1, "Use None and create inside."),
        ("A generator:", ["Stores all values", "Produces values lazily with yield", "Is a list subclass", "Runs in parallel"], 1, "Memory-efficient iteration."),
        ("dict lookup average complexity:", ["O(n)", "O(1)", "O(log n)", "O(n log n)"], 1, "Hash table."),
        ("asyncio is best for:", ["CPU-heavy math", "Many concurrent I/O-bound tasks", "GPU", "Parallel CPU"], 1, "Single-threaded event loop."),
        ("is vs ==:", ["Same", "is compares identity, == compares equality", "is compares value", "== compares identity"], 1, "Use is for None."),
        ("A decorator is:", ["A class attribute", "A callable that takes a function and returns a wrapped function", "A type hint", "A metaclass only"], 1, "Use functools.wraps to keep metadata."),
        ("@dataclass generates:", ["Database tables", "__init__, __repr__, __eq__ (and more with options)", "Async methods", "Serializers"], 1, "frozen=True for immutability."),
    ],
    "security": [
        ("Passwords should be stored using:", ["MD5", "SHA-256 plain", "A slow salted hash like bcrypt/scrypt/Argon2", "Encryption with a shared key"], 2, "Slow, salted, tunable work factor."),
        ("SQL injection is prevented primarily by:", ["Escaping quotes manually", "Parameterized queries / prepared statements", "Hiding errors", "HTTPS"], 1, "Never concatenate user input into SQL."),
        ("CSRF is a risk mainly for:", ["Bearer-token APIs", "Cookie-authenticated browser sessions", "gRPC", "CLI tools"], 1, "Use SameSite cookies + CSRF tokens."),
        ("A JWT signature guarantees:", ["Confidentiality", "Integrity/authenticity of the claims", "Revocation", "Encryption"], 1, "JWTs are readable by anyone; validate iss/aud/exp."),
        ("OAuth 2.0 Authorization Code + PKCE is recommended for:", ["Server-to-server only", "Public clients like SPAs and mobile apps", "Password grants", "Nothing"], 1, "PKCE prevents code interception."),
        ("IDOR (Insecure Direct Object Reference) is fixed by:", ["Rate limiting", "Checking the caller is authorized for that specific object", "HTTPS", "Longer IDs only"], 1, "Authorization per object, not just per endpoint."),
        ("XSS is mitigated by:", ["Output encoding + CSP", "Stronger passwords", "HTTPS only", "Rate limits"], 0, "Escape by context; avoid innerHTML with untrusted data."),
        ("mTLS means:", ["Only server presents a certificate", "Both client and server authenticate with certificates", "No TLS", "Multi-tenant TLS"], 1, "Common for service-to-service auth."),
        ("Secrets should be stored in:", ["Git", "A secrets manager / vault, injected at runtime", "Docker image", "Logs"], 1, "Rotate and audit access."),
        ("401 vs 403:", ["Same", "401 = not authenticated, 403 = authenticated but not allowed", "403 = not authenticated", "401 = server error"], 1, "Return 404 to hide existence when appropriate."),
    ],
}


def all_questions():
    out = []
    for subj, items in _RAW.items():
        for i, (q, opts, a, why) in enumerate(items):
            out.append({"id": "%s-%d" % (subj, i + 1), "subject": subj, "q": q, "options": opts, "a": a, "why": why})
    return out


QUESTIONS = all_questions()
BY_ID = {q["id"]: q for q in QUESTIONS}
